name: Run Tests on PR

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 17

      - name: Validate Gradle wrapper
        run: ./gradlew wrapper

      - name: Build with Gradle
        run: ./gradlew build